spring:
  profiles:
    active: local

logging:
  level:
    org:
      springframework:
        data:
          elasticsearch:
            client:
              WIRE: trace

elasticsearch:
  url: localhost:9200
